### ISSUE TITLE
Connect ielektronik to prisjakt

### ISSUE THREAD

**Issue by orgotech-folke** [orgotech/ielektronik.se#1]
The customer wants us to connect prisjakt and project. When an visitors makes an order we are going to add the order ID and the order total to the URL that we iframe. 

We are going to add the iframe when an order is successful. We are getting all data from the klarna module.

The iframe is going to look like:
`<iframe src="https://tbs.tradedoubler.com/report?organization=2088958&event=355336&orderNumber=<?= ORDER_ID_HERE ?>&orderValue=<?= ORDER_TOTAL_HERE ?>&currency=SEK&tduid=<?= $_SESSION['TRADEDOUBLER'] ?>&type=iframe"frameborder="0" width="1" height="1"></iframe>`

I has already fixed so that the user gets the TRADEDOUBLER ID. But that can also be the wrong way but its in the /index.php file.

**Comment by orgotech-robert** [comment]
http://dev.tradedoubler.com/tracking/advertiser/

There is a "Testing the implementation" section in the manual page with steps how to test the connection, it also says "If the trackback is not correctly implemented you will get a detailed error message that indicates which part of the implementation is not functioning properly."

If someone has access to the login at Tradedoubler, then a login there could be beneficial to test the implementation.

**Comment by orgotech-folke** [comment]
Jag kontaktade Prestaworks (skaparna av klarnamodulen) igår om att de ska lägga in en iframe vid ett lyckat köp. Har fortfarande inte hört något mer ifall de har påbörjat ärendet eller inte.

**Comment by orgotech-folke** [comment]
Jag gjorde ett testköp och blev skickad till framsidan utan en köpbekräftelse. Har Kontaktat Daniel angående detta men inväntar svar.

**Comment by orgotech-folke** [comment]
Fick ett svar från Anna och det verkar som att Prisjakt ska kunna dela ut inloggningar så man själv kan söka på sina ordrar.

**Comment by orgotech-folke** [comment]
Pratade med prisjakt och man ska kunna höra av sig till dem så det går snabbare än att kontakta anna. E-postadressen är **affiliateprogram@prisjakt.nu**.

**Comment by orgotech-folke** [comment]
Pratade med Klarna och man kan tydligen få en development inloggning. Har ansökt men kommer troligen att få inloggningen tills nästa vecka.

Har skickat iväg ett meddelande till Daniel på Prestaworks angående att vidareutveckla modulen på Tisdag (2017-02-14) istället.

**Comment by orgotech-folke** [comment]
Har nu fått en dev nyckel av klarna som jag kommer att testa med.

EID: 8701
Shared Secret: XQjz52mbFaUWCED

**Comment by orgotech-folke** [comment]
Har nu installerat en kopia av hela hemsidan på dev.ielektronik.se.

**Comment by orgotech-folke** [comment]
Kontaktade Daniel på Prestaworks angående att försöka fixa vår prestashop redan idag under dev.ielektronok.se
